services:
  postgres:
    image: 'postgres:15'
    container_name: clipers-postgres
    environment:
      - 'POSTGRES_DB=clipers_db'
      - 'POSTGRES_PASSWORD=clipers_password'
      - 'POSTGRES_USER=clipers_user'
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clipers-network

  redis:
    image: 'redis:7-alpine'
    container_name: clipers-redis
    ports:
      - '6379:6379'
    networks:
      - clipers-network

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: clipers-rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - clipers-network

volumes:
  postgres_data:

networks:
  clipers-network:
    driver: bridge
