services:
  postgres:
    image: 'postgres:17'
    container_name: clipers-postgres
    environment:
      - 'POSTGRES_DB=clipers_db'
      - 'POSTGRES_PASSWORD=clipers_password'
      - 'POSTGRES_USER=clipers_user'
      - 'POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clipers-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clipers_user -d clipers_db"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redis:
    image: 'redis:7-alpine'
    container_name: clipers-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - clipers-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: clipers-rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_USER=clipers'
      - 'RABBITMQ_DEFAULT_PASS=clipers123'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - clipers-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  clipers-network:
    driver: bridge
