version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: clipers-postgres
    environment:
      POSTGRES_DB: clipers_db
      POSTGRES_USER: clipers_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-clipers_password}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clipers_user -d clipers_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  clipers-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clipers-backend
    environment:
      SPRING_PROFILES_ACTIVE: coolify
      SERVER_PORT: 8080
      DATABASE_URL: jdbc:postgresql://postgres:5432/clipers_db
      DATABASE_USERNAME: clipers_user
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-clipers_password}
      JWT_SECRET: ${JWT_SECRET:-mySecretKey123456789012345678901234567890123456789012345678901234567890}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/test/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data: