server:
  port: 8080

spring:
  application:
    name: clipers-backend
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clipers_db}
    username: ${SPRING_DATASOURCE_USERNAME:clipers_user}
    password: ${SPRING_DATASOURCE_PASSWORD:089056}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: ${REDIS_TIMEOUT:2000ms}
    lettuce:
      pool:
        max-active: ${REDIS_POOL_MAX_ACTIVE:8}
        max-wait: ${REDIS_POOL_MAX_WAIT:-1ms}
        max-idle: ${REDIS_POOL_MAX_IDLE:8}
        min-idle: ${REDIS_POOL_MIN_IDLE:0}
        
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:"*"}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
    max-age: ${CORS_MAX_AGE:3600}

# AI + ATS Integration Configuration
ai:
  score:
    weights:
      ai: ${AI_WEIGHT_AI:0.6}
      ats: ${AI_WEIGHT_ATS:0.3}
      profile: ${AI_WEIGHT_PROFILE:0.1}

# Cache Configuration
cache:
  ttl: ${CACHE_TTL:1800}  # 30 minutes in seconds

# Logging Configuration
logging:
  level:
    root: INFO
    com.clipers: DEBUG
    com.clipers.ai.integration: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/clipers-backend.log
    max-size: 10MB
    max-history: 7
    total-size-cap: 100MB
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 100MB
      history: 7
      clean-history-on-start: false

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  info:
    title: Clipers Backend API
    description: API for Clipers Backend with AI + ATS Integration
    version: 1.0.0
    contact:
      name: Clipers Team
      email: team@clipers.com
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html
  packages-to-scan: com.clipers.ai.integration.controller
  paths-to-match: /api/integration/**

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer}